### PR TITLE
This year in Redox

### PR DESCRIPTION
**Pull request by ticki**

### CODE REVIEW

**Comment by jackpot51** [comment]
Looks good! I do agree with @pythoneer about adding a list of article links

**Comment by ticki** [comment]
I propose that we publish to reddit on around 00:00.

**Comment by pythoneer** [comment]
we had 00:00 already in Australia – so what timezone do you referring to?

**Comment by jackpot51** [comment]
@ticki sounds good. Also, tge link to TFS logo needs to be fixed

**Comment by ticki** [comment]
@pythoneer haha, good point. Well, I'm refering to whatever zone is the most active on /r/rust.

**Comment by ticki** [comment]
https://www.reddit.com/r/rust/about/traffic/

**Comment by jackpot51** [comment]
@ticki The TFS logo needs to be embedded as an img tag to function

**Comment by pythoneer** [comment]
i was thinking about this traffic site too, but i don't think it says anything about stats we're interested in. I would say just stick with one of the north american time zones.

**Comment by jackpot51** [comment]
@pythoneer I merged in the list
@ticki I fixed the TFS logo

**Pull request merged**
