### PR TITLE
translate doc

### PR DESCRIPTION
**Pull request by origel**
translate doc page to Chinese

### CODE REVIEW

**Comment by jackpot51** [comment]
Thanks!

**Comment by origel** [comment]
You are welcome. What can I do next? I am a java web developer. I familiar with such as java, spring, nginx, html and css.

**Comment by jackpot51** [comment]
I hope @ticki fixes the chat room limit, we discuss most development decisions there. Do you want to learn Rust?

**Comment by origel** [comment]
Yes, I have read some rust document and has basic knowledges.

**Pull request merged**
